### ISSUE TITLE
How to run the app? Where is the back end API server?

### ISSUE THREAD

**Issue by gordon518** [edsion11/Angular-forum#1]
How to run the app? Where is the back end API server at port of 1234?

**Comment by edsion11** [comment]
Okay，may be in terminal key this: "npm start",it will running in you 4200 port, the backend server code will be uploaded one day。

**Comment by edsion11** [comment]
> How to run the app? Where is the back end API server at port of 1234?

Okay，may be in terminal key this: "npm start",it will running in you 4200 port, the backend server code will be uploaded one day。
